/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ecemessage"
 * 	found in "Ecemessage.asn1"
 * 	`asn1c -R`
 */

#include "Ecemessage.h"

static int
memb_vitesse_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 50)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_vitesse_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..50) */,
	-1};
static asn_per_constraints_t asn_PER_memb_vitesse_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 6,  6,  0,  50 }	/* (0..50) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_Ecemessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Ecemessage, vitesse),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_vitesse_constr_2, &asn_PER_memb_vitesse_constr_2,  memb_vitesse_constraint_1 },
		0, 0, /* No default value */
		"vitesse"
		},
};
static const ber_tlv_tag_t asn_DEF_Ecemessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Ecemessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 } /* vitesse */
};
static asn_SEQUENCE_specifics_t asn_SPC_Ecemessage_specs_1 = {
	sizeof(struct Ecemessage),
	offsetof(struct Ecemessage, _asn_ctx),
	asn_MAP_Ecemessage_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Ecemessage = {
	"Ecemessage",
	"Ecemessage",
	&asn_OP_SEQUENCE,
	asn_DEF_Ecemessage_tags_1,
	sizeof(asn_DEF_Ecemessage_tags_1)
		/sizeof(asn_DEF_Ecemessage_tags_1[0]), /* 1 */
	asn_DEF_Ecemessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_Ecemessage_tags_1)
		/sizeof(asn_DEF_Ecemessage_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ecemessage_1,
	1,	/* Elements count */
	&asn_SPC_Ecemessage_specs_1	/* Additional specs */
};

