/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ecemessage"
 * 	found in "Ecemessage.asn1"
 * 	`asn1c -R`
 */

#ifndef	_Ecemessage_H_
#define	_Ecemessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Ecemessage */
typedef struct Ecemessage {
	long	 vitesse;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ecemessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ecemessage;

#ifdef __cplusplus
}
#endif

#endif	/* _Ecemessage_H_ */
#include <asn_internal.h>
