// Generated by gencpp from file ece_msgs/Insertion.msg
// DO NOT EDIT!


#ifndef ECE_MSGS_MESSAGE_INSERTION_H
#define ECE_MSGS_MESSAGE_INSERTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ece_msgs/ReferencePosition.h>

namespace ece_msgs
{
template <class ContainerAllocator>
struct Insertion_
{
  typedef Insertion_<ContainerAllocator> Type;

  Insertion_()
    : point_insertion()
    , confirmation_insertion(false)  {
    }
  Insertion_(const ContainerAllocator& _alloc)
    : point_insertion(_alloc)
    , confirmation_insertion(false)  {
  (void)_alloc;
    }



   typedef  ::ece_msgs::ReferencePosition_<ContainerAllocator>  _point_insertion_type;
  _point_insertion_type point_insertion;

   typedef uint8_t _confirmation_insertion_type;
  _confirmation_insertion_type confirmation_insertion;





  typedef boost::shared_ptr< ::ece_msgs::Insertion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ece_msgs::Insertion_<ContainerAllocator> const> ConstPtr;

}; // struct Insertion_

typedef ::ece_msgs::Insertion_<std::allocator<void> > Insertion;

typedef boost::shared_ptr< ::ece_msgs::Insertion > InsertionPtr;
typedef boost::shared_ptr< ::ece_msgs::Insertion const> InsertionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ece_msgs::Insertion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ece_msgs::Insertion_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ece_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ece_msgs': ['/home/david/catkin_ws/src/ece_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ece_msgs::Insertion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ece_msgs::Insertion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece_msgs::Insertion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece_msgs::Insertion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece_msgs::Insertion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece_msgs::Insertion_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ece_msgs::Insertion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "445e7910d0486ca2159677b916542c18";
  }

  static const char* value(const ::ece_msgs::Insertion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x445e7910d0486ca2ULL;
  static const uint64_t static_value2 = 0x159677b916542c18ULL;
};

template<class ContainerAllocator>
struct DataType< ::ece_msgs::Insertion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ece_msgs/Insertion";
  }

  static const char* value(const ::ece_msgs::Insertion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ece_msgs::Insertion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Point d'insertion : 8 octet \n\
ReferencePosition point_insertion\n\
\n\
# Confirmation insertion : 1 octet\n\
bool confirmation_insertion\n\
================================================================================\n\
MSG: ece_msgs/ReferencePosition\n\
int64 latitude # 0.1 micro degree\n\
int64 longitude # 0.1 micro degree\n\
int32 altitude\n\
\n\
int64 LATITUDE_UNAVAILABLE = 900000001\n\
int64 LONGITUDE_UNAVAILABLE = 1800000001\n\
int32 ALTITUDE_UNAVAILABLE = 800001\n\
";
  }

  static const char* value(const ::ece_msgs::Insertion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ece_msgs::Insertion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point_insertion);
      stream.next(m.confirmation_insertion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Insertion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ece_msgs::Insertion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ece_msgs::Insertion_<ContainerAllocator>& v)
  {
    s << indent << "point_insertion: ";
    s << std::endl;
    Printer< ::ece_msgs::ReferencePosition_<ContainerAllocator> >::stream(s, indent + "  ", v.point_insertion);
    s << indent << "confirmation_insertion: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.confirmation_insertion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ECE_MSGS_MESSAGE_INSERTION_H
