// Generated by gencpp from file ece_msgs/Platoon.msg
// DO NOT EDIT!


#ifndef ECE_MSGS_MESSAGE_PLATOON_H
#define ECE_MSGS_MESSAGE_PLATOON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ece_msgs/IDs.h>
#include <ece_msgs/ReferencePosition.h>

namespace ece_msgs
{
template <class ContainerAllocator>
struct Platoon_
{
  typedef Platoon_<ContainerAllocator> Type;

  Platoon_()
    : id_vt(0)
    , id_platoon(0)
    , ids()
    , nombre_vehicules(0)
    , reference_position()  {
    }
  Platoon_(const ContainerAllocator& _alloc)
    : id_vt(0)
    , id_platoon(0)
    , ids(_alloc)
    , nombre_vehicules(0)
    , reference_position(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _id_vt_type;
  _id_vt_type id_vt;

   typedef uint8_t _id_platoon_type;
  _id_platoon_type id_platoon;

   typedef  ::ece_msgs::IDs_<ContainerAllocator>  _ids_type;
  _ids_type ids;

   typedef uint8_t _nombre_vehicules_type;
  _nombre_vehicules_type nombre_vehicules;

   typedef  ::ece_msgs::ReferencePosition_<ContainerAllocator>  _reference_position_type;
  _reference_position_type reference_position;





  typedef boost::shared_ptr< ::ece_msgs::Platoon_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ece_msgs::Platoon_<ContainerAllocator> const> ConstPtr;

}; // struct Platoon_

typedef ::ece_msgs::Platoon_<std::allocator<void> > Platoon;

typedef boost::shared_ptr< ::ece_msgs::Platoon > PlatoonPtr;
typedef boost::shared_ptr< ::ece_msgs::Platoon const> PlatoonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ece_msgs::Platoon_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ece_msgs::Platoon_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ece_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ece_msgs': ['/home/user/catkin_ws/src/ece_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ece_msgs::Platoon_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ece_msgs::Platoon_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece_msgs::Platoon_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ece_msgs::Platoon_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece_msgs::Platoon_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ece_msgs::Platoon_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ece_msgs::Platoon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e04a40bb6fe3969e75a1973bd60b5977";
  }

  static const char* value(const ::ece_msgs::Platoon_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe04a40bb6fe3969eULL;
  static const uint64_t static_value2 = 0x75a1973bd60b5977ULL;
};

template<class ContainerAllocator>
struct DataType< ::ece_msgs::Platoon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ece_msgs/Platoon";
  }

  static const char* value(const ::ece_msgs::Platoon_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ece_msgs::Platoon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ID Vt : 3 bits \n\
uint8 id_vt\n\
\n\
# ID platoon : 3 bits\n\
uint8 id_platoon\n\
\n\
# ID autres véhicules platoon : 3 bits\n\
IDs ids \n\
\n\
# Nombre de véhicules : 3 bits\n\
uint8 nombre_vehicules\n\
\n\
# Destination : 8 octets\n\
ReferencePosition reference_position\n\
================================================================================\n\
MSG: ece_msgs/IDs\n\
uint8 ID\n\
uint8 position\n\
================================================================================\n\
MSG: ece_msgs/ReferencePosition\n\
int64 latitude # 0.1 micro degree\n\
int64 longitude # 0.1 micro degree\n\
PositionConfidenceEllipse position_confidence\n\
Altitude altitude\n\
\n\
int64 LATITUDE_UNAVAILABLE = 900000001\n\
int64 LONGITUDE_UNAVAILABLE = 1800000001\n\
\n\
================================================================================\n\
MSG: ece_msgs/PositionConfidenceEllipse\n\
uint16 semi_major_confidence # cm\n\
uint16 semi_minor_confidence # cm\n\
uint16 semi_major_orientation # 0.1 degree\n\
\n\
uint16 SEMI_AXIS_LENGTH_OUT_OF_RANGE = 4094\n\
uint16 SEMI_AXIS_LENGTH_UNAVAILABLE = 4095\n\
\n\
================================================================================\n\
MSG: ece_msgs/Altitude\n\
int32 value # 0.01 meter\n\
uint8 confidence\n\
\n\
int32 VALUE_REFERENCE_ELLIPSOID_SURFACE = 0\n\
int32 VALUE_ONE_CENTIMETER = 1\n\
int32 VALUE_UNAVAILABLE = 800001\n\
\n\
uint8 CONFIDENCE_1CM = 0\n\
uint8 CONFIDENCE_2CM = 1\n\
uint8 CONFIDENCE_5CM = 2\n\
uint8 CONFIDENCE_10CM = 3\n\
uint8 CONFIDENCE_20CM = 4\n\
uint8 CONFIDENCE_50CM = 5\n\
uint8 CONFIDENCE_1M = 6\n\
uint8 CONFIDENCE_2M = 7\n\
uint8 CONFIDENCE_5M = 8\n\
uint8 CONFIDENCE_10M = 9\n\
uint8 CONFIDENCE_20M = 10\n\
uint8 CONFIDENCE_50M = 11\n\
uint8 CONFIDENCE_100M = 12\n\
uint8 CONFIDENCE_200M = 13\n\
uint8 CONFIDENCE_OUT_OF_RANGE = 14\n\
uint8 CONFIDENCE_UNAVAILABLE = 15\n\
";
  }

  static const char* value(const ::ece_msgs::Platoon_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ece_msgs::Platoon_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id_vt);
      stream.next(m.id_platoon);
      stream.next(m.ids);
      stream.next(m.nombre_vehicules);
      stream.next(m.reference_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Platoon_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ece_msgs::Platoon_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ece_msgs::Platoon_<ContainerAllocator>& v)
  {
    s << indent << "id_vt: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id_vt);
    s << indent << "id_platoon: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id_platoon);
    s << indent << "ids: ";
    s << std::endl;
    Printer< ::ece_msgs::IDs_<ContainerAllocator> >::stream(s, indent + "  ", v.ids);
    s << indent << "nombre_vehicules: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.nombre_vehicules);
    s << indent << "reference_position: ";
    s << std::endl;
    Printer< ::ece_msgs::ReferencePosition_<ContainerAllocator> >::stream(s, indent + "  ", v.reference_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ECE_MSGS_MESSAGE_PLATOON_H
