/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Rectangle"
 * 	found in "Rectangle.asn1"
 * 	`asn1c -no-gen-example`
 */

#include "Rectangle.h"

static int
height_2_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	unsigned long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const unsigned long *)sptr;
	
	if(1 /* No applicable constraints whatsoever */) {
		(void)value; /* Unused variable */
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
width_3_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	unsigned long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const unsigned long *)sptr;
	
	if(1 /* No applicable constraints whatsoever */) {
		(void)value; /* Unused variable */
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
memb_height_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	unsigned long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const unsigned long *)sptr;
	
	if(1 /* No applicable constraints whatsoever */) {
		(void)value; /* Unused variable */
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_width_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	unsigned long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const unsigned long *)sptr;
	
	if(1 /* No applicable constraints whatsoever */) {
		(void)value; /* Unused variable */
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_oer_constraints_t asn_OER_type_height_constr_2 CC_NOTUSED = {
	{ 0, 1 }	/* (0..MAX) */,
	-1};
static asn_per_constraints_t asn_PER_type_height_constr_2 CC_NOTUSED = {
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (0..MAX) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_width_constr_3 CC_NOTUSED = {
	{ 0, 1 }	/* (0..MAX) */,
	-1};
static asn_per_constraints_t asn_PER_type_width_constr_3 CC_NOTUSED = {
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (0..MAX) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_height_constr_2 CC_NOTUSED = {
	{ 0, 1 }	/* (0..MAX) */,
	-1};
static asn_per_constraints_t asn_PER_memb_height_constr_2 CC_NOTUSED = {
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (0..MAX) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_width_constr_3 CC_NOTUSED = {
	{ 0, 1 }	/* (0..MAX) */,
	-1};
static asn_per_constraints_t asn_PER_memb_width_constr_3 CC_NOTUSED = {
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (0..MAX) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_specifics_t asn_SPC_height_specs_2 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_height_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_height_2 = {
	"height",
	"height",
	&asn_OP_NativeInteger,
	asn_DEF_height_tags_2,
	sizeof(asn_DEF_height_tags_2)
		/sizeof(asn_DEF_height_tags_2[0]), /* 1 */
	asn_DEF_height_tags_2,	/* Same as above */
	sizeof(asn_DEF_height_tags_2)
		/sizeof(asn_DEF_height_tags_2[0]), /* 1 */
	{ &asn_OER_type_height_constr_2, &asn_PER_type_height_constr_2, height_2_constraint },
	0, 0,	/* No members */
	&asn_SPC_height_specs_2	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_width_specs_3 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_width_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_width_3 = {
	"width",
	"width",
	&asn_OP_NativeInteger,
	asn_DEF_width_tags_3,
	sizeof(asn_DEF_width_tags_3)
		/sizeof(asn_DEF_width_tags_3[0]), /* 1 */
	asn_DEF_width_tags_3,	/* Same as above */
	sizeof(asn_DEF_width_tags_3)
		/sizeof(asn_DEF_width_tags_3[0]), /* 1 */
	{ &asn_OER_type_width_constr_3, &asn_PER_type_width_constr_3, width_3_constraint },
	0, 0,	/* No members */
	&asn_SPC_width_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Rectangle_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Rectangle, height),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_height_2,
		0,
		{ &asn_OER_memb_height_constr_2, &asn_PER_memb_height_constr_2,  memb_height_constraint_1 },
		0, 0, /* No default value */
		"height"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Rectangle, width),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_width_3,
		0,
		{ &asn_OER_memb_width_constr_3, &asn_PER_memb_width_constr_3,  memb_width_constraint_1 },
		0, 0, /* No default value */
		"width"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Rectangle, booleen),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"booleen"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Rectangle, string),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"string"
		},
};
static const ber_tlv_tag_t asn_DEF_Rectangle_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Rectangle_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 2, 0, 0 }, /* booleen */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* height */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 }, /* width */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 3, 0, 0 } /* string */
};
static asn_SEQUENCE_specifics_t asn_SPC_Rectangle_specs_1 = {
	sizeof(struct Rectangle),
	offsetof(struct Rectangle, _asn_ctx),
	asn_MAP_Rectangle_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Rectangle = {
	"Rectangle",
	"Rectangle",
	&asn_OP_SEQUENCE,
	asn_DEF_Rectangle_tags_1,
	sizeof(asn_DEF_Rectangle_tags_1)
		/sizeof(asn_DEF_Rectangle_tags_1[0]), /* 1 */
	asn_DEF_Rectangle_tags_1,	/* Same as above */
	sizeof(asn_DEF_Rectangle_tags_1)
		/sizeof(asn_DEF_Rectangle_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Rectangle_1,
	4,	/* Elements count */
	&asn_SPC_Rectangle_specs_1	/* Additional specs */
};

