# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ece_msgs/BasicContainer.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ece_msgs.msg

class BasicContainer(genpy.Message):
  _md5sum = "3f4b2605638c093c7a78f93ee5ddc5aa"
  _type = "ece_msgs/BasicContainer"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ID expediteur
uint8 ID_exp

# ID destinataire
uint8 ID_dest

# Phase de plattoning
Phase phase

================================================================================
MSG: ece_msgs/Phase
# Phase de plattoning
uint8 value

uint8 INIT = 0
uint8 INSERTION = 1
uint8 DESINSERTION = 2
uint8 FEU = 3
uint8 FREINAGE_URG = 4"""
  __slots__ = ['ID_exp','ID_dest','phase']
  _slot_types = ['uint8','uint8','ece_msgs/Phase']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ID_exp,ID_dest,phase

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BasicContainer, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.ID_exp is None:
        self.ID_exp = 0
      if self.ID_dest is None:
        self.ID_dest = 0
      if self.phase is None:
        self.phase = ece_msgs.msg.Phase()
    else:
      self.ID_exp = 0
      self.ID_dest = 0
      self.phase = ece_msgs.msg.Phase()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.ID_exp, _x.ID_dest, _x.phase.value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.phase is None:
        self.phase = ece_msgs.msg.Phase()
      end = 0
      _x = self
      start = end
      end += 3
      (_x.ID_exp, _x.ID_dest, _x.phase.value,) = _get_struct_3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.ID_exp, _x.ID_dest, _x.phase.value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.phase is None:
        self.phase = ece_msgs.msg.Phase()
      end = 0
      _x = self
      start = end
      end += 3
      (_x.ID_exp, _x.ID_dest, _x.phase.value,) = _get_struct_3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
